[tool.poetry]
name        = "issues_fs_dev_role_librarian"
version     = "v0.2.1"
description = "Issues-FS__Dev__Role__Librarian"
authors     = ["Dinis Cruz <dinis.cruz@owasp.org>"]
license     = "Apache 2.0"
readme      = "README.md"
homepage    = "https://github.com/owasp-sbot/Issues-FS__Dev__Role__Librarian"
repository  = "https://github.com/owasp-sbot/Issues-FS__Dev__Role__Librarian"

[tool.poetry.dependencies]
python            = "^3.12"
osbot-utils       = "*"
issues-fs-cli     = "*"

[build-system]
requires = ["poetry-core>=1.9.1"]
build-backend = "poetry.core.masonry.api"

